### ISSUE TITLE
Dev: `build` script is silent before & after `quick-build`, causing appearance of hanging

### ISSUE THREAD

**Issue by vjjft** [tjjfvi/escad#76]
causes appearance of build hanging, especially as it occurs after output `Done` from `create-index-better`
(related: `quick-build` is currently silent (in all cases?))

**Comment by tjjfvi** [comment]
> ```
> ...
> [21:02:25] /Volumes/X5/Dev/escad/packages/playground/static/bundled/project/node_modules/@escad/client-3d-viewer/src/index.ts [index has not changed]
> [21:02:25] /Volumes/X5/Dev/escad/packages/playground/static/bundled/project/node_modules/@escad/builtins/src/index.ts [index has not changed]
> [21:02:25] Done
> 
> > escad@0.0.0 lint
> > test $(tail -c1 package.json) && echo >> package.json; npm run lint-check -- --fix
> 
> 
> > escad@0.0.0 lint-check
> > test ! $(tail -c1 package.json) && eslint '{packages,examples}/**/*.{ts,tsx}' "--fix"
> 
> 
> > escad@0.0.0 quick-build
> > tsc -b packages
> 
> $PS1
> ```
Doesn't look silent to me 🚎

**Comment by tjjfvi** [comment]
Irrelevant due to #113
